version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: custom-nginx
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html     # Serve static site files
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Use custom NGINX config
    restart: always

